# Generated by Django 2.0 on 2017-12-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='lists.List'),
        ),
    ]
